# Temp Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  selector:
    matchLabels:
      app: nextjs
  replicas: 1
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
        - name: nextjs
          image: "ghcr.io/afope/devops-project:$TAG"
          ports:
            - containerPort: 3000
